// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-01-06 10:28:10.046582299 +0330 +0330 m=+0.027311580

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Amirhossein Yaghoubi",
            "url": "https://yaghoubi.dev",
            "email": "amir.yaghoubi.dev@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/user": {
            "post": {
                "description": "Insert or Update User ACL",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Insert or Update User",
                "parameters": [
                    {
                        "description": "Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.updateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.updateUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/auth.errorMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/auth.errorMessage"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a user by username",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete a user",
                "parameters": [
                    {
                        "description": "Delete payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.deleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.deleteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/auth.errorMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/auth.errorMessage"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.deleteRequest": {
            "type": "object",
            "required": [
                "username"
            ],
            "properties": {
                "username": {
                    "type": "string",
                    "example": "USERNAME"
                }
            }
        },
        "auth.deleteResponse": {
            "type": "object",
            "properties": {
                "is_deleted": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "auth.errorMessage": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "something really bad happend"
                }
            }
        },
        "auth.publishACL": {
            "type": "object",
            "properties": {
                "allowed_retain": {
                    "type": "boolean"
                },
                "max_qos": {
                    "type": "integer"
                },
                "pattern": {
                    "type": "string",
                    "example": "foo/bar/baz"
                }
            }
        },
        "auth.subACL": {
            "type": "object",
            "properties": {
                "max_qos": {
                    "type": "integer"
                },
                "pattern": {
                    "type": "string",
                    "example": "foo/bar/baz"
                }
            }
        },
        "auth.updateUserRequest": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "mountpoint": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "publish_acl": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/auth.publishACL"
                    }
                },
                "subscribe_acl": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/auth.subACL"
                    }
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "auth.updateUserResponse": {
            "type": "object",
            "properties": {
                "result": {
                    "type": "string",
                    "example": "ok"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:9595",
	BasePath:    "/api/v1/",
	Schemes:     []string{},
	Title:       "Vernemq API",
	Description: "API wrapper around vernemq broker",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
